spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # OBS: Se for a primeira vez use create, se não use validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
